name: CI/CD Pipeline

# Trigger the workflow on push to main branch or pull request to main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Jobs to run
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Use the Node.js version compatible with your project

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run unit tests with Vitest
      - name: Run unit tests
        run: npm run test:unit

      # Run E2E tests with Cypress
      - name: Run E2E tests
        run: npm run test:e2e

  build:
    runs-on: ubuntu-latest
    needs: test # Ensure the build job runs only if tests pass
    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the project
      - name: Build project
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build # Ensure the deploy job runs only if the build succeeds
    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the project
      - name: Build project
        run: npm run build

      # Deploy to GitHub Pages (example)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist